export default {
    serverHost: '/api',
    tokenKey: 'JSESSIONID_SIN',
    userInfo: 'userinfo',
    SITE_BASE_URL: __SITE_BASE_URL__,
    BASE_RESTFUL_URL: __REST_BASE_URL__,
    REST_SOCKET_URL: __REST_SOCKET_URL__,
    CDN_STATIC_URL: __CDN_STATIC_URL__,
    REST_FILE_URL: __REST_FILE_URL__,
    REST_CHAT_URL: __REST_CHAT_URL__,
    SVR_IMAGE_URL: `${__REST_FILE_URL__}down/?path=`,
    SITE_VERSION: __SITE_VERSION__,
    PLATFORM: __PLATFORM__,
    SITE_AUTHCENTER: __SITE_AUTHCENTER__,
    SITE_VRHOME: __SITE_VRHOME__,
    SITE_PREFIX_URL: `${__SITE_VRHOME__}views/`,
    SITE_MALLHOME: __SITE_MALLHOME__,

    sek: '1234123412ABCDEF',
    sei: 'ABCDEF1234123412'
};
